package main

import (
	"time"

	"github.com/google/uuid"
	"github.com/jakeleesh/rssagg/internal/database"
)

// Optimization
// JSON Response key names are same as key names in User struct in database
// Can't change struct manually, generated by sqlc
// Instead, create own User type
// Nearly identical, only difference is add JSON tags
// Should be snake case convention
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

// All this does is return a new User struct where populate with stuff from database User
// Purpose is to own the shape that's being returned over HTTP responses
func databaseUserToUser(dbUser database.User) User {
	return User{
		ID:        dbUser.ID,
		CreatedAt: dbUser.CreatedAt,
		UpdatedAt: dbUser.UpdatedAt,
		Name:      dbUser.Name,
	}
}
